Document project
socrata-platform/soql-redshift-adapter pull request #23
Opened 2023-12-11 20:09 UTC by ds2643

2023-12-12 21:17 UTC, ds2643 commented on README.md
> +This repository [implements](store-redshift/src/main/scala/com/socrata/service/RedshiftSecondary.scala) a [secondary](https://github.com/socrata-platform/data-coordinator/blob/405523e986467c14d507952
Due to the excessive use of links, I recommend reviewing via Github rendering.

2023-12-12 21:40 UTC, PaulMTT commented on README.md
> +mvn compile
We can remove `mvn compile`,  as `mvn install` will do the same but better.
Specifically:
Since we have a multi-module project, our sibling modules can depend on each other and this is done the traditional maven dependency way. 
`mvn install` will cache the built artifacts locally, so that projects depending on this artifact will see/receive the freshest copy.
I've seen mixed behavior on how things handle this, so it's better to be explicit for now, meaning "I want all my modules to be compiled, and even if you try to pull from cache - the cached version should be the latest"

2023-12-12 21:41 UTC, zachlefevre approved these changes

2023-12-12 23:23 UTC, zachlefevre commented on README.md
> +mvn compile
Is there ever a reason to do `mvn compile`?

2023-12-12 23:24 UTC, zachlefevre requested changes
Paul's suggestion.

2023-12-12 23:25 UTC, zachlefevre approved these changes

2023-12-12 23:36 UTC, PaulMTT commented on README.md
> +mvn compile
Yes, you can invoke that on the sub-project directly, if that is the place you are modifying/testing.

So for example:
Given: You are poking and iterating on coming in store.
Then: You can just `mvn compile`

And otherwise originally:
Given: Poking something in store/server, then modified something in common
Then:`mvn install`, since you modified a dependency.

So really I guess both, depending on what you are doing, are applicable.

2023-12-13 00:12 UTC, ds2643 commented on README.md
> +mvn compile
- [ ] Remove `mvn compile`.

2023-12-13 14:38 UTC, PaulMTT approved these changes

2023-12-14 21:05 UTC, PaulMTT approved these changes

2024-01-17 22:17 UTC, merged