Make provenanced types order correctly
socrata-platform/soql-redshift-adapter pull request #36
Opened 2024-01-19 23:12 UTC by zachlefevre

2024-01-19 23:28 UTC, rjmac requested changes

2024-01-19 23:28 UTC, rjmac commented on common-redshift/src/main/scala/com/socrata/common/sqlizer/RedshiftExprSqlFactory.scala
> +            d"""(/* soql_compress_provenanced */ ISNULL(${text}, '') + '-;-' + ISNULL(${bigint} :: text, ''))"""
I don't think this second `ISNULL` should be here; a null number-subcolumn means the value as a whole is null.

2024-01-19 23:28 UTC, rjmac commented on common-redshift/src/main/scala/com/socrata/common/sqlizer/SoQLSqlizer.scala
> +            d"(/* soql_extract_compressed_value */ split_part($origSql, '-;-', 2))"
This should cast the the result to bigint, or it'll sort like a text value instead of a number value.

2024-01-19 23:28 UTC, rjmac commented on common-redshift/src/main/scala/com/socrata/common/sqlizer/SoQLSqlizer.scala
> +            d"(/* soql_extract_compressed_provenance */ split_part($origSql, '-;-', 1))",
`nullif(split_part(etcetc), '')` - this recovers the null provenance back into nullness.

2024-01-22 17:16 UTC, rjmac commented on common-redshift/src/main/scala/com/socrata/common/sqlizer/RedshiftExprSqlFactory.scala
> +            d"""(/* soql_compress_provenanced */ ISNULL(${text}, '') + '-;-' + ${bigint} :: text)"""
In the postgresql secondary, the convention is "caller adds parens if it might be necessary".  I don't know if you're following that convention (the outermost parens here suggest you're not) but if you are, then that `${bigint}` need parens around it to make sure the `::` binds properly.

2024-01-22 17:17 UTC, zachlefevre commented on common-redshift/src/main/scala/com/socrata/common/sqlizer/RedshiftExprSqlFactory.scala
> +            d"""(/* soql_compress_provenanced */ ISNULL(${text}, '') + '-;-' + ${bigint} :: text)"""
We do follow the same convention, but to be safe I'll force them here as well. parens are free in SQL :)

2024-01-22 17:22 UTC, rjmac commented on common-redshift/src/main/scala/com/socrata/common/sqlizer/RedshiftExprSqlFactory.scala
> +            d"""(/* soql_compress_provenanced */ ISNULL(${text}, '') + '-;-' + (${bigint} :: text))"""
No, I meant `(${bigint}) :: text` - the idea is that if somehow you the bigint expression expands to an expression containing operators, you want the `::` to apply to that entire expression.

It isn't obvious to me how that could happen (it'd have to be something _really weird_) but might as well nip that potential codegen bug in the bud.

2024-01-22 17:37 UTC, rjmac approved these changes

2024-01-22 17:45 UTC, closed without merging