Execute SLQ in query endpoint
socrata-platform/soql-redshift-adapter pull request #39
Opened 2024-01-24 18:47 UTC by zachlefevre

2024-01-24 19:58 UTC, zachlefevre commented on server-redshift/src/main/scala/com/socrata/server/executor/TypeTransformer.scala
> +case object TypeTransformer {
Much of this was taken from soql-postgres-adapter.

2024-01-24 19:58 UTC, zachlefevre commented on server-redshift/src/main/scala/com/socrata/server/newquery/controller/NewQueryController.scala
> +    Using.resource(storeDataSource.getConnection) { conn =>
This was *not* taken from soql postgres adapter.

2024-01-24 19:59 UTC, zachlefevre commented on store-redshift/src/test/scala/com/socrata/store/service/RedshiftSecondaryTest.scala
>    val datasetInfo = DatasetInfo(
here I am using the integration tests to populate my DB. I've made the dataset and it's columns more realistic.

2024-01-24 19:59 UTC, zachlefevre commented on store-redshift/src/test/scala/com/socrata/store/service/RedshiftSecondaryTest.scala
> +          new ColumnId(1) -> SoQLID(100),
but not too realistic :)

2024-01-24 21:51 UTC, dnabilali approved these changes

2024-01-24 21:51 UTC, dnabilali commented on common-redshift/src/main/resources/application-prod.yaml
>        max-size: 11
do we want to merge these changes? won't it be better to leave it the way it has been and just update the .env locally for each of us?

2024-01-24 21:51 UTC, PaulMTT requested changes

2024-01-25 17:56 UTC, zachlefevre commented on common-redshift/src/main/resources/db/meta/20241101-meta-init.xml
> +            drop table if exists datasets;
This migration gets the DB in a state that the migrations can run.
I do not have a strong opinion. I'll change it.

2024-01-25 22:44 UTC, zachlefevre commented on store-redshift/src/main/resources/application-integration.yaml
> +    db-kind: postgresql
integrations tests do not run in Jenkins.

2024-01-25 22:45 UTC, zachlefevre commented on server-redshift/src/main/resources/application.yaml
> +      username: ${REDSHIFT_USER}
server-redshift does not have a set of profiles.

2024-01-25 23:36 UTC, PaulMTT requested changes

2024-01-25 23:36 UTC, PaulMTT commented on common-redshift/src/main/resources/application-dev.yaml
> +    username: ${POSTGRES_USER}
You can turn off dev services here, so that the passthrough env stuff gets used.

2024-01-25 23:36 UTC, PaulMTT commented on server-redshift/src/main/resources/application.yaml
> +    username: ${POSTGRES_USER}
What I meant before is to move this into dev/test/integration/prod profiles, leaving the plain application.yaml undeclared (profiles do not exist yet), as that works out better for the dev server. However actually, we don't need this! The common application.yaml handles all these bits. The reason we are missing profiles in this project is because we don't have anything special to handle yet.

2024-01-25 23:36 UTC, PaulMTT commented on store-redshift/src/main/resources/application-integration.yaml
> +    username: ${POSTGRES_USER}
This should be the `....devservices: enabled:true` ... `quarkus:quarkus` bit, so if and when we run integration it will spin up a container.

2024-01-25 23:38 UTC, PaulMTT commented on common-redshift/src/main/resources/application-dev.yaml
> +    username: ${POSTGRES_USER}
The dev profile will be the default for everyone running this app by default.
While using a container makes sense, our redshift is a persistent live connection so I like the idea of dev being default local.

2024-01-29 20:23 UTC, zachlefevre commented
@PaulMTT Please rereview when you get a chance.

2024-01-30 15:46 UTC, PaulMTT approved these changes

2024-01-30 16:16 UTC, merged